services:
  basdb:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    ports:
      - 8080:8080
    container_name: adminer
    depends_on:
      basdb:
        condition: service_healthy

  baspi:
    build: ./api
    environment:
      - PORT=4000
      - DB_TYPE = postgres
      - DB_HOST=basdb
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_NAME=postgres
      - DB_PASSWORD=password
      - CLIENT_URL=http://localhost:5173
    command: ["npm", "run", "full"]
    depends_on:
      basdb:
        condition: service_healthy
    volumes:
      - ./api:/app

  client:
    build: ./client
    environment:
      - VITE_GRAPHQL_API_URL=http://localhost:5000/graph
    command: ["npm", "run", "dev"]
    volumes:
      - ./client:/app

  gateway:
    image: nginx
    ports:
      - 5000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - baspi
      - client
